from core.exceptions import ConflictError


class ProductAlreadyInCartError(ConflictError):
    pass
